echo ""
echo ""
echo "--------------------------------------------"
echo "--------------------------------------------"
echo ""
echo "       Welcome to the BRAIN-AWS system"
echo "© 2015-16  UW-Madison. All rights reserved"
echo ""
echo "--------------------------------------------"
echo "--------------------------------------------"
echo ""

