./write_option_dict $tmp_dir/option.json scheduler_info_path $scheduler_info_path 
./write_option_dict $tmp_dir/option.json key_pair_path $key_pair_path 
./write_option_dict $tmp_dir/option.json input_dir $input_dir 
./write_option_dict $tmp_dir/option.json image_id $image_id 
./write_option_dict $tmp_dir/option.json security_group_ids $security_group_ids 
./write_option_dict $tmp_dir/option.json server_type $server_type 
./write_option_dict $tmp_dir/option.json max_num_servers $max_num_servers 
./write_option_dict $tmp_dir/option.json logpath $logpath 
./write_option_dict $tmp_dir/option.json results_dir $results_dir 
./write_option_dict $tmp_dir/option.json local_run_script $local_run_script 
./write_option_dict $tmp_dir/option.json binpath $binpath
./write_option_dict $tmp_dir/option.json scheduler_log_path $scheduler_log_path
./write_option_dict $tmp_dir/option.json job_done_dir $job_done_dir
./write_option_dict $tmp_dir/option.json log_change_only $log_change_only
./write_option_dict $tmp_dir/option.json raw_result_fname $raw_result_fname
./write_option_dict $tmp_dir/option.json debug_level $debug_level
./write_option_dict $tmp_dir/option.json sInstanceIds $sInstanceIds
./write_option_dict $tmp_dir/option.json notermination $notermination
